CREATE DATABASE UNIDAS;
GO

USE UNIDAS;
GO

CREATE TABLE PESSOA(
	idPessoa INT PRIMARY KEY IDENTITY(1,1),
	nomePessoa VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE TELEFONE(
	idTelefone INT PRIMARY KEY IDENTITY(1,1),
	idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	numeroTelefone CHAR(11) NOT NULL
);
GO

CREATE TABLE EMAIL(
	idEmail INT PRIMARY KEY IDENTITY(1,1),
	idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	end_email VARCHAR(256) NOT NULL UNIQUE
);
GO

CREATE TABLE CNH(
	idCnh INT PRIMARY KEY IDENTITY(1,1),
	idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	descricao CHAR(20) NOT NULL UNIQUE
);
GO