CREATE DATABASE CLINICA_VITOR

USE CLINICA_VITOR

CREATE TABLE CLINICA(
	idclinica TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeClinica VARCHAR(10) NOT NULL UNIQUE
);
GO

CREATE TABLE VETERINARIO(
	idveterinario TINYINT PRIMARY KEY IDENTITY (1,1),
	idclinica TINYINT FOREIGN KEY REFERENCES CLINICA(idclinica),
	nomeVeterinario VARCHAR(20) NOT NULL
);
GO

CREATE TABLE DONO(
	iddono SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeDono VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TIPO(
	idtipo SMALLINT PRIMARY KEY IDENTITY(1,1),
	tipoAnimal VARCHAR(10) NOT NULL
);
GO

CREATE TABLE RACA(
	idraca TINYINT PRIMARY KEY IDENTITY(1,1),
	idtipo SMALLINT FOREIGN KEY REFERENCES TIPO(idtipo),
	raca VARCHAR(10) NOT NULL
);
GO


CREATE TABLE PET(
	idpet TINYINT PRIMARY KEY IDENTITY(1,1),
	iddono SMALLINT FOREIGN KEY REFERENCES DONO(iddono),
	idraca TINYINT FOREIGN KEY REFERENCES RACA(idraca),
	nomePet VARCHAR(10) NOT NULL UNIQUE
);
GO

DROP TABLE PET 


CREATE TABLE ATENDIMENTO(
	idatendimento TINYINT PRIMARY KEY IDENTITY(1,1),
	idpet TINYINT FOREIGN KEY REFERENCES PET(idpet),
	idveterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idveterinario),
	senhaAtendimento SMALLINT NOT NULL
);
GO

DROP TABLE ATENDIMENTO
