CREATE DATABASE LOCADORA
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA(
	idempresa TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(20) NOT NULL UNIQUE
);
GO

CREATE TABLE VEICULO(
	idveiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idempresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idempresa),
	idmodelo SMALLINT FOREIGN KEY REFERENCES MODELO(idmodelo),
	anoVeiculo DATE NOT NULL UNIQUE	
);
GO

CREATE TABLE MODELO(
	idmodelo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idmarca TINYINT FOREIGN KEY REFERENCES MARCA(idmarca),
	nomeModelo VARCHAR(10) NOT NULL UNIQUE
);
GO

CREATE TABLE MARCA(
	idmarca TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(10) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEL(
	idaluguel TINYINT PRIMARY KEY IDENTITY(1,1),
	idcliente TINYINT FOREIGN KEY REFERENCES CLIENTES(idcliente),
	valorAluguel VARCHAR(10) NOT NULL UNIQUE
);
GO

CREATE TABLE CLIENTES(
	idcliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeCliente VARCHAR(10) NOT NULL UNIQUE
);
GO