CREATE DATABASE CLINICA
GO

USE CLINICA;
GO

CREATE TABLE CLINICA(
	idclinica TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeClinica VARCHAR(10) NOT NULL UNIQUE
);
GO

CREATE TABLE VETERINARIO(
	idveterinario TINYINT PRIMARY KEY IDENTITY (1,1),
	idclinica TINYINT FOREIGN KEY REFERENCES CLINICA(idclinica),
	nomeVeterinario VARCHAR(20) NOT NULL
);
GO

CREATE TABLE ATENDIMENTO(
	idatendimento TINYINT PRIMARY KEY IDENTITY(1,1),
	idveterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idveterinario),
	senhaAtendimento SMALLINT NOT NULL
);
GO

CREATE TABLE PET(
	idpet SMALLINT PRIMARY KEY IDENTITY(1,1),
	idraca SMALLINT FOREIGN KEY REFERENCES RACA(idraca),
	iddono SMALLINT FOREIGN KEY REFERENCES DONO(iddono),
	nomePet VARCHAR(10)
);
GO

CREATE TABLE DONO(
	iddono SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeDono VARCHAR(20) NOT NULL
);
GO

CREATE TABLE RACA(
	idraca TINYINT PRIMARY KEY IDENTITY(1,1),
	idtipo SMALLINT FOREIGN KEY REFERENCES TIPO(idtipo),
	raca VARCHAR(10) NOT NULL
);
GO

CREATE TABLE TIPO(
	idtipo SMALLINT PRIMARY KEY IDENTITY(1,1),
	tipoAnimal VARCHAR(10) NOT NULL
);
GO