USE CATALOGO;


INSERT INTO GENERO(nomeGenero)
VALUES ('COMEDIA')

SELECT * FROM GENERO
SELECT * FROM FILME

INSERT INTO FILME (idGenero,tituloFilme)
VALUES (1,'RAMBO PROGRAMADO PARA MATAR'), (1,'THE AVENGERS - OS VINGADORES 2012'), (2,'GHOST'), (2, 'DIARIO DE UMA PAIXÃO')

INSERT INTO FILME (idGenero, tituloFilme)
VALUES (3, 'HEHE BOY')


UPDATE FILME
SET tituloFilme = 'GENTE GRANDE'
WHERE idFilme = 9

