CREATE TABLE GENERO (
	IdGenero TINYINT PRIMARY KEY IDENTITY,
    nomeGenero VARCHAR(30)
);
GO

CREATE TABLE FILME (
	idfilme SMALLINT PRIMARY KEY IDENTITY(1,1),
	idGenero TINYINT FOREIGN KEY REFERENCES GENERO(idGenero),
	tituloFilme VARCHAR(70)
);
GO